### ISSUE TITLE
NodeBB not working on heroku but works on local machine

### ISSUE THREAD

**Issue by Shivaraman-iyer** [NodeBB/NodeBB#2544]
Hi,
I've been trying to follow the process of installing NodeBB on Heroku, and I have been able to successfully run it in my local machine(Ubuntu 14.04). But, it seems like on the heroku server I am getting errors... Following is my output of "heroku logs" 

2014-12-22T14:28:38.968514+00:00 heroku[web.1]: Starting process with command `node loader.js --no-daemon`
2014-12-22T14:29:39.355080+00:00 heroku[web.1]: Error R10 (Boot timeout) -> Web process failed to bind to $PORT within 60 seconds of launch
2014-12-22T14:29:39.355331+00:00 heroku[web.1]: Stopping process with SIGKILL
2014-12-22T14:29:40.152569+00:00 heroku[web.1]: Process exited with status 137
2014-12-22T14:29:40.168501+00:00 heroku[web.1]: State changed from starting to crashed
2014-12-22T14:29:40.169139+00:00 heroku[web.1]: State changed from crashed to starting
2014-12-22T14:29:42.978814+00:00 heroku[web.1]: Starting process with command `node loader.js --no-daemon`
2014-12-22T14:30:43.197962+00:00 heroku[web.1]: Error R10 (Boot timeout) -> Web process failed to bind to $PORT within 60 seconds of launch
2014-12-22T14:30:43.198156+00:00 heroku[web.1]: Stopping process with SIGKILL
2014-12-22T14:30:43.949869+00:00 heroku[web.1]: Process exited with status 137
2014-12-22T14:30:43.964372+00:00 heroku[web.1]: State changed from starting to crashed

Could you please help me with the problem.

Thank you

**Comment by Shivaraman-iyer** [comment]
Well I tested with openshift, just to see what is happening and it works perfectly without having to think twice.
Is there a specific reason for nodebb to not work on heroku?

**Comment by julianlam** [comment]
> 2014-12-30T20:32:41.529506+00:00 app[web.1]: 2014-12-30T20:32:41.529Z - info: NodeBB attempting to listen on: seekbigger.co.uk:55676

I don't think the URL should be shown here. Please post your config as @barisusakli suggested.

**Comment by Shivaraman-iyer** [comment]
{
    "base_url": "http://community.seekbigger.co.uk",
    "port": "4568",
    "secret": "c64bc1c0-42f9-4313-948a-8e5a978be0ad",
    "bind_address": "seekbigger.co.uk",
    "database": "mongo",
    "mongo": {
        "host": "ds043200.mongolab.com",
        "port": "43200",
        "username": "database_user",
        "password": "*********",
        "database": "heroku_app32898684"
    },
    "bcrypt_rounds": 12,
    "upload_path": "/public/uploads",
    "use_port": false,
    "relative_path": ""
}

**Comment by julianlam** [comment]
Remove `bind_address` from config, it should be `0.0.0.0`, or missing altogether for Heroku, as you don't know the network interface IP address...

**Comment by Shivaraman-iyer** [comment]
@julianlam That works like a charm! thanks a lot. It would be nice if you could add this particular point in the tutorial itself.

Thanks a lot again!

**Comment by harianus** [comment]
I've the same issue as above, but I don't have the `bind_address` in my `config.json`

```js
// config.json
{
    "url": "https://[HIDDEN].herokuapp.com",
    "secret": "[HIDDEN]",
    "database": "redis",
    "redis": {
        "host": "[HIDDEN].redistogo.com",
        "port": "[HIDDEN]",
        "password": "[HIDDEN]",
        "database": "0"
    }
}
```

**Comment by AXtime** [comment]
@harianus I had the same issue with v0.6.1 and was able to get this running by making a simple change to the loader.js file.  I changed the getPorts routine to first check for heroku's PORT env variable.

line 185 (should be in the getPorts())
changed from 

`var port = nconf.get('port') || nconf.get('PORT') || urlObject.port || 4567;`

to 

`var port = process.env.PORT || nconf.get('port') || nconf.get('PORT') || urlObject.port || 4567;`

**Comment by Lwdthe1** [comment]
I fixed it by doing the following:
* Change ProcFile to read as follows: `web: node app.js`
* In webserver.js, change this line `listen()`:  `var port = parseInt(nconf.get('port'), 10);` to `var port = process.env.PORT || parseInt(nconf.get('port'), 10);` because heroku controls what port you use through process.env.PORT.
* In config.js, make your url field to the address of your herokuapp

**Comment by pitaj** [comment]
Hmmm... yes it looks like `nconf.get('PORT')` should come before `nconf.get('port')`

**Comment by julianlam** [comment]
Heroku doesn't work on `loader.js`? Right... that explains it, since `app.js` had the port section moved out to `loader.js`. Standby...

**Comment by julianlam** [comment]
Out of curiosity, what happens when you have the `Procfile` contents as:

```
web: node loader.js --no-daemon
```

?

**Comment by stillli** [comment]
Make change according @Lwdthe1 , but still get error like this
```
Error: Failed to lookup view "categories" in views directory "/app/build/public/templates"
2017-06-26T19:57:03.759116+00:00 app[web.1]:     at EventEmitter.render (/app/node_modules/express/lib/application.js:580:17)
2017-06-26T19:57:03.759117+00:00 app[web.1]:     at ServerResponse.render (/app/node_modules/express/lib/response.js:971:7)
2017-06-26T19:57:03.759118+00:00 app[web.1]:     at content (/app/src/middleware/render.js:70:15)
......
```

**Comment by pitaj** [comment]
run `./nodebb build`, and check if `build/public/templates/categories.tpl` exists

**Comment by Lwdthe1** [comment]
Yeah, I never ran into the lookup error @stillli is facing, but I ran into another issue before I ran `./nodebb build` and it worked.

**Comment by Lwdthe1** [comment]
@julianlam It just breaks Heroku because it can' find necessary files that loader.js needs because of file path issues.

**Comment by riyadhzen** [comment]
@julianlam, I am running nodebb under dokku (which is similar to heroku) and Regarding your request "Out of curiosity, what happens when you have the Procfile contents as:
```web: node loader.js --no-daemon```". I got the following error ```Failed to lookup view "categories" in views directory "/usr/src/app/build/public/templates" ```
Changing Procfile to ```web: node app.js``` fixed the issue

**Comment by riyadhzen** [comment]
Interesting ```web: node app.js``` Procfile is causing the same error, but ```node app.js``` Procfile doesn't cause the error.

I think I might have to move my part to another issue, as this is dealing with dokku not heroku

**Comment by rssbands** [comment]
> I fixed it by doing the following:
> 
> * Change ProcFile to read as follows: `web: node app.js`
> * In webserver.js, change this line `listen()`:  `var port = parseInt(nconf.get('port'), 10);` to `var port = process.env.PORT || parseInt(nconf.get('port'), 10);` because heroku controls what port you use through process.env.PORT.
> * In config.js, make your url field to the address of your herokuapp (i.g `"https://yourapp.herokuapp.com"`

Ji everyone. Now I have this problem.((
2019-09-03T10:08:46.000000+00:00 app[api]: Build succeeded
2019-09-03T10:09:39.200481+00:00 heroku[web.1]: State changed from starting to crashed
2019-09-03T10:09:39.084174+00:00 heroku[web.1]: Error R10 (Boot timeout) -> Web process failed to bind to $PORT within 60 seconds of
2019-09-03T10:09:39.084174+00:00 heroku[web.1]: Stopping process with SIGKILL
2019-09-03T10:09:39.177829+00:00 heroku[web.1]: Process exited with status 137
2019-09-03T10:09:41.502915+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=thawing-plains-91095.
2019-09-03T10:09:42.422796+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=thawing-pl
