### ISSUE TITLE
Updating 0.5.x to 0.6.1 - "upgrading permissions" issue

### ISSUE THREAD

**Issue by EvSpirit** [NodeBB/NodeBB#2740]
While upgrading to 0.6.1, I got the following error:

```
19/2 16:44 [5942] - error: [2014/11/11] Error encountered while upgrading permissions
19/2 16:44 [5942] - error: [upgrade] Errors were encountered while updating the NodeBB schema: WRONGTYPE Operation against a key holding the wrong kind of value
```

It seems the problem is in Groups.get somewhere. It fails when calling Groups.list, and Groups.get gives err. 

My current version is 0.5.3

**Comment by julianlam** [comment]
Hi @EvSpirit, what git hash were you attempting to upgrade to? This issue should have been resolved (see #2655) in this commit: https://github.com/NodeBB/NodeBB/commit/06238f689415e216cf131e9e295fae8c4e9566a2#diff-a37e6ea9475b7ffd3058569dae961e22

**Comment by EvSpirit** [comment]
Hi @julianlam! 

Yes, I saw that ticket, but I've already checked upgrade.js and it's up-to-date. My current rev hash is cb32d68e3acfd0c3aa7ef7bc84b58f6adaea2b2d.

**Comment by julianlam** [comment]
If you're up to date, then is this no longer an issue?

**Comment by EvSpirit** [comment]
@julianlam , the issue is still the same. I had the same revision when I reported the problem. Do you need some extra info?

As far as I could understand, the problem is somewhere here:
```Java
						Groups.list({showSystemGroups: true}, function(err, groups) {
							if (err) {
								return next(err);
							}

							async.eachLimit(cids, 50, function(cid, next) {
								upgradePrivileges(cid, groups, next);
							}, next);
						});
```

Lines 253-261.

**Comment by julianlam** [comment]
@EvSpirit So just to confirm: You're running v0.6.1, and NodeBB does not complain that you're out-of-date?

If you still have a copy of your database from before you updated to v0.6.x, I can take a look at it...

**Comment by EvSpirit** [comment]
No, my current version is 0.5.3 and I'm trying to upgrade to 0.6.x. And I cannot run 0.6.x cause ./nodebb upgrade fails.

**Comment by julianlam** [comment]
Resolved in latest commits to both master and `v0.6.x`. Thanks!
