### ISSUE TITLE
No category accessible for new registered users

### ISSUE THREAD

**Issue by Couby** [NodeBB/NodeBB#2800]
Something just noticing, my new registered users have no content to access to once they are logged.

http://forums.fabriques-alternatives.org

They don't see anymore categories, nor content, and if accessing via a direct link they are told they don't have rights to. All content is public and accessible for ghests...

I created a group and add them to it, but that doesn't change anything.

v0.6.1

Could it be something related again to the arm architecture of the server ?

**Comment by Couby** [comment]
Could it be related to bcrypt as I already encountered some specific problems with it https://github.com/NodeBB/NodeBB/issues/2650 ?

**Comment by julianlam** [comment]
Doubtful. This is the latest commit on v0.6.x branch, correct? Not `master`?

**Comment by Couby** [comment]
Yes, latest commit on v0.6.x branch + brcrypt in place of bcryptjs.

**Comment by julianlam** [comment]
Please review the access control settings for the `registered-users` group in each category. They need at least the first two permissions in order to read posts.

A fresh install of v0.6.x branch does not exhibit this bug for me.

**Comment by Couby** [comment]
Mmmh, I have nothing in access control boxes, like in the picture of this issue https://github.com/NodeBB/NodeBB/issues/2707 .

**Comment by EvSpirit** [comment]
I wrote some thoughts in #2707, I think it should be reviewed by developers. If you need a hotfix, you can either patch your redis db (but that's difficult a bit) or change some lines of code in categories.js (see 2707 for details). That helped me and I fixed all access rights.

**Comment by Couby** [comment]
@EvSpirit thanks for the info. I made a try but no success. I notice in logs I have errors so maybe there are some other problems elsewhere.
I'll try to make a fresh install beside this one and see how it works before reporting those new problems.

**Comment by EvSpirit** [comment]
@Couby , by the way, try to check your client-side logs when opening categories access rights window, do you have any errors in a console?

**Comment by Couby** [comment]
@EvSpirit damn, now I can see groups in access rights window, what I didn't have yesterday !
Client-side I have the following warning : 
> TypeError: privilegeList is null                                              categories.js:377:7

I checked frontend with my user-test and he still can't see categories once connected...

**Comment by Couby** [comment]
@EvSpirit Mmmh, well, now I can set access control for registered users. It's empty for all categories and changing it works for my test-user :-). I simply think your fix worked !
I don't know why yesterday I didn't see it...

Many thanks @EvSpirit !!!

I'll make a pre-prod version of my forum to test next update before applying it :-)

Thanks all.
