### ISSUE TITLE
duplicate key error index issue

### ISSUE THREAD

**Issue by exomarty** [NodeBB/NodeBB#5265]
Please include the following information when submitting a bug report/issue:

* NodeBB 1.4.0
* Database Mongo

I got that error on the upgrade and after removing like 30 objects on the db managed to run and complete the upgrade ( https://community.nodebb.org/topic/9939/index-with-name-_key_1_value_-1-already-exists-with-different-options/11)

sadly the error keep appearing while nodebb is running

```
8/12 02:17 [28995] - error: Error creating index exception: E11000 duplicate key error index: exodef.objects.$_key_1_value_-1 dup key: { : "ip:recent", : ip" }
8/12 02:17 [28995] - info: [database] Checking database indices done!
8/12 02:17 [28995] - error:  MongoError: exception: E11000 duplicate key error index: exodef.objects.$_key_1_value_-1 dup key: { : "ip:recent", : "ip" }
    at Function.MongoError.create (/var/foroexodo/nodebb/node_modules/mongodb/node_modules/mongodb-core/lib/error.js:31:11)
    at /var/foroexodo/nodebb/node_modules/mongodb/node_modules/mongodb-core/lib/connection/pool.js:462:72
    at authenticateStragglers (/var/foroexodo/nodebb/node_modules/mongodb/node_modules/mongodb-core/lib/connection/pool.js:410:16)
    at null.messageHandler (/var/foroexodo/nodebb/node_modules/mongodb/node_modules/mongodb-core/lib/connection/pool.js:444:5)
    at Socket.<anonymous> (/var/foroexodo/nodebb/node_modules/mongodb/node_modules/mongodb-core/lib/connection/connection.js:306:22)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at Socket.Readable.push (_stream_readable.js:111:10)
    at TCP.onread (net.js:537:20)
[cluster] Child Process (28995) has exited (code: 0, signal: null)

```

```
8/12 02:19 [29164] - error: Error creating index exception: E11000 duplicate key error index: exodef.objects.$_key_1_value_-1 dup key: { : "analytics:uniquevisitors", : "1481108400000" }
8/12 02:19 [29164] - info: [database] Checking database indices done!
8/12 02:19 [29164] - error:  MongoError: exception: E11000 duplicate key error index: exodef.objects.$_key_1_value_-1 dup key: { : "analytics:uniquevisitors", : "1481108400000" }
    at Function.MongoError.create (/var/foroexodo/nodebb/node_modules/mongodb/node_modules/mongodb-core/lib/error.js:31:11)
    at /var/foroexodo/nodebb/node_modules/mongodb/node_modules/mongodb-core/lib/connection/pool.js:462:72
    at authenticateStragglers (/var/foroexodo/nodebb/node_modules/mongodb/node_modules/mongodb-core/lib/connection/pool.js:410:16)
    at null.messageHandler (/var/foroexodo/nodebb/node_modules/mongodb/node_modules/mongodb-core/lib/connection/pool.js:444:5)
    at Socket.<anonymous> (/var/foroexodo/nodebb/node_modules/mongodb/node_modules/mongodb-core/lib/connection/connection.js:306:22)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at Socket.Readable.push (_stream_readable.js:111:10)
    at TCP.onread (net.js:537:20)
[cluster] Child Process (29164) has exited (code: 0, signal: null)

```
i tried to delete them but they keep appearing agan and again different ips
seems like they appear on ip and analytics keys
not sure if this is related but i´m unable to change my theme even restarting the old one stays maybe because the system is unable to do a clean restart

**Comment by julianlam** [comment]
@barisusakli Would dropping the indices and letting NodeBB rebuild them be an acceptable course of action here?

**Comment by barisusakli** [comment]
Might work, the logs posted here look like they are happening on app start.

**Comment by exomarty** [comment]
yes, they happen on start
main problem is i cant change my theme or update it

**Comment by barisusakli** [comment]
When you drop the indices and restart nodebb do you get the same error? If so you need to remove the documents that have the duplicate keys.

**Comment by exomarty** [comment]
i removed all them before upgrade, then new ones appeared
how do i drop the indices?

i been removing the documents but got tired after manual deleting 50 of them

**Comment by barisusakli** [comment]
`db.objects.dropIndexes();` then try restarting.

**Comment by exomarty** [comment]
![screenshot_2](https://cloud.githubusercontent.com/assets/10746278/21024601/776ed4c4-bd85-11e6-8d59-f0fa1d287df7.png)



```
 ./nodebb log

Hit Ctrl-C to exit


NodeBB v1.4.0 Copyright (C) 2013-2014 NodeBB Inc.
This program comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it under certain cond                  itions.
For the full license, please visit: http://www.gnu.org/copyleft/gpl.html

Clustering enabled: Spinning up 6 process(es).

8/12 20:28 [4325] - info: Time: Thu Dec 08 2016 20:28:15 GMT+0100 (CET)
8/12 20:28 [4325] - info: Initializing NodeBB v1.4.0
8/12 20:28 [4325] - info: [database] Checking database indices.
8/12 20:28 [4337] - info: [database] Checking database indices.
8/12 20:28 [4331] - info: [database] Checking database indices.
8/12 20:28 [4349] - info: [database] Checking database indices.
8/12 20:28 [4343] - info: [database] Checking database indices.
8/12 20:28 [4355] - info: [database] Checking database indices.
8/12 20:28 [4337] - info: [database] Checking database indices done!
8/12 20:28 [4343] - info: [database] Checking database indices done!
8/12 20:28 [4349] - info: [database] Checking database indices done!
8/12 20:28 [4355] - info: [database] Checking database indices done!
8/12 20:28 [4325] - info: [database] Checking database indices done!
8/12 20:28 [4355] - info: initializing NodeBB ...
8/12 20:28 [4349] - info: initializing NodeBB ...
8/12 20:28 [4343] - info: initializing NodeBB ...
8/12 20:28 [4325] - info: initializing NodeBB ...
8/12 20:28 [4337] - info: initializing NodeBB ...
8/12 20:28 [4355] - warn: [plugins/nodebb-plugin-poll] Hook `filter:post.save` is deprecated, please use `filter:post.create` instead.
8/12 20:28 [4337] - warn: [plugins/nodebb-plugin-poll] Hook `filter:post.save` is deprecated, please use `filter:post.create` instead.
8/12 20:28 [4325] - warn: [plugins/nodebb-plugin-poll] Hook `filter:post.save` is deprecated, please use `filter:post.create` instead.
8/12 20:28 [4343] - warn: [plugins/nodebb-plugin-poll] Hook `filter:post.save` is deprecated, please use `filter:post.create` instead.
8/12 20:28 [4349] - warn: [plugins/nodebb-plugin-poll] Hook `filter:post.save` is deprecated, please use `filter:post.create` instead.

8/12 20:28 [4325] - warn: [plugins/load] The following plugins may not be compatible with your version of NodeBB. This may cause unintended behaviour or crashing. In the event of an unresponsive NodeBB caused by this plugin, run `./nodebb reset -p PLUGINNAME` to disable it.
  * nodebb-plugin-autolock

8/12 20:28 [4355] - info: [reputation-rules] settings loaded
8/12 20:28 [4343] - info: [reputation-rules] settings loaded
8/12 20:28 [4337] - info: [reputation-rules] settings loaded
8/12 20:28 [4355] - info: Routes added
8/12 20:28 [4343] - info: Routes added
8/12 20:28 [4349] - info: [reputation-rules] settings loaded
8/12 20:28 [4349] - info: Routes added
8/12 20:28 [4337] - info: Routes added
8/12 20:28 [4325] - info: [reputation-rules] settings loaded
8/12 20:28 [4325] - info: Routes added
8/12 20:28 [4343] - info: NodeBB Ready
8/12 20:28 [4337] - info: NodeBB Ready
8/12 20:28 [4355] - info: NodeBB Ready
8/12 20:28 [4349] - info: NodeBB Ready
8/12 20:28 [4343] - info: Enabling 'trust proxy'
8/12 20:28 [4355] - info: Enabling 'trust proxy'
8/12 20:28 [4337] - info: Enabling 'trust proxy'
8/12 20:28 [4349] - info: Enabling 'trust proxy'
8/12 20:28 [4343] - info: NodeBB is now listening on: 0.0.0.0:4570
8/12 20:28 [4355] - info: NodeBB is now listening on: 0.0.0.0:4572
8/12 20:28 [4349] - info: NodeBB is now listening on: 0.0.0.0:4571
8/12 20:28 [4337] - info: NodeBB is now listening on: 0.0.0.0:4569
8/12 20:28 [4325] - info: NodeBB Ready
8/12 20:28 [4325] - info: Enabling 'trust proxy'
8/12 20:28 [4325] - info: NodeBB is now listening on: 0.0.0.0:4567
8/12 20:28 [4331] - error: Error creating index exception: E11000 duplicate key error index: exodef.objects.$_key_1_value_-1 dup key: { : "ip:recent", : "35.164.70.59" }
8/12 20:28 [4331] - info: [database] Checking database indices done!
8/12 20:28 [4331] - error:  MongoError: exception: E11000 duplicate key error index: exodef.objects.$_key_1_value_-1 dup key: { : "ip:recent", : "35.164.70.59" }
    at Function.MongoError.create (/var/foroexodo/nodebb/node_modules/mongodb/node_modules/mongodb-core/lib/error.js:31:11)
    at /var/foroexodo/nodebb/node_modules/mongodb/node_modules/mongodb-core/lib/connection/pool.js:462:72
    at authenticateStragglers (/var/foroexodo/nodebb/node_modules/mongodb/node_modules/mongodb-core/lib/connection/pool.js:410:16)
    at null.messageHandler (/var/foroexodo/nodebb/node_modules/mongodb/node_modules/mongodb-core/lib/connection/pool.js:444:5)
    at Socket.<anonymous> (/var/foroexodo/nodebb/node_modules/mongodb/node_modules/mongodb-core/lib/connection/connection.js:306:22)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at Socket.Readable.push (_stream_readable.js:111:10)
    at TCP.onread (net.js:537:20)
[cluster] Child Process (4331) has exited (code: 0, signal: null)

```

**Comment by barisusakli** [comment]
Are you sure the `dropIndexes` command is working and you are running it on the correct database? You can check by `db.objects.getIndexes()`

If those don't work running the following aggreation to get all the problematic objects.

```
db.objects.aggregate([
	{$match: {_key: "ip:recent"}},
	{$group: {_id: {value: "$value"}, count: {$sum: 1}}},
	{$match: {count: {$gte: 2}}}
]);
```

This will show all the problem objects modify the key to find the others.

**Comment by exomarty** [comment]
yes, i was on the incorrect db
![screenshot_3](https://cloud.githubusercontent.com/assets/10746278/21024999/0806f2ae-bd87-11e6-80fa-34c476724d5d.png)

but now nodebb stopped working

```
./nodebb log

Hit Ctrl-C to exit

8/12 20:43 [6443] - info: [database] Checking database indices.
8/12 20:43 [6443] - info: [database] Checking database indices done!
8/12 20:43 [6456] - info: [database] Checking database indices.
8/12 20:43 [6455] - info: [database] Checking database indices.
8/12 20:43 [6456] - info: [database] Checking database indices done!
8/12 20:43 [6455] - info: [database] Checking database indices done!
8/12 20:43 [6449] - info: [database] Checking database indices.
8/12 20:43 [6473] - info: [database] Checking database indices.
8/12 20:43 [6473] - info: [database] Checking database indices done!
8/12 20:43 [6449] - info: [database] Checking database indices done!
8/12 20:43 [6466] - info: [database] Checking database indices done!
8/12 20:43 [6443] - error: MongoError: connection 0 to 127.0.0.1:27017 timed out
    at Function.MongoError.create (/var/foroexodo/nodebb/node_modules/mongodb/node_modules/mongodb-core/lib/error.js:29:11)
    at Socket.<anonymous> (/var/foroexodo/nodebb/node_modules/mongodb/node_modules/mongodb-core/lib/connection/connection.js:173:20)
    at Socket.g (events.js:260:16)
    at emitNone (events.js:67:13)
    at Socket.emit (events.js:166:7)
    at Socket._onTimeout (net.js:333:8)
    at _runOnTimeout (timers.js:524:11)
    at _makeTimerTimeout (timers.js:515:3)
    at Timer.unrefTimeout (timers.js:584:5)
8/12 20:43 [6443] - error:  MongoError: connection 0 to 127.0.0.1:27017 timed out
    at Function.MongoError.create (/var/foroexodo/nodebb/node_modules/mongodb/node_modules/mongodb-core/lib/error.js:29:11)
    at Socket.<anonymous> (/var/foroexodo/nodebb/node_modules/mongodb/node_modules/mongodb-core/lib/connection/connection.js:173:20)
    at Socket.g (events.js:260:16)
    at emitNone (events.js:67:13)
    at Socket.emit (events.js:166:7)
    at Socket._onTimeout (net.js:333:8)
    at _runOnTimeout (timers.js:524:11)
    at _makeTimerTimeout (timers.js:515:3)
    at Timer.unrefTimeout (timers.js:584:5)
[cluster] Child Process (6443) has exited (code: 0, signal: null)
8/12 20:43 [6456] - error: MongoError: connection 0 to 127.0.0.1:27017 timed out
    at Function.MongoError.create (/var/foroexodo/nodebb/node_modules/mongodb/node_modules/mongodb-core/lib/error.js:29:11)
    at Socket.<anonymous> (/var/foroexodo/nodebb/node_modules/mongodb/node_modules/mongodb-core/lib/connection/connection.js:173:20)
    at Socket.g (events.js:260:16)
    at emitNone (events.js:67:13)
    at Socket.emit (events.js:166:7)
    at Socket._onTimeout (net.js:333:8)
    at _runOnTimeout (timers.js:524:11)
    at _makeTimerTimeout (timers.js:515:3)
    at Timer.unrefTimeout (timers.js:584:5)
8/12 20:43 [6456] - error:  MongoError: connection 0 to 127.0.0.1:27017 timed out
    at Function.MongoError.create (/var/foroexodo/nodebb/node_modules/mongodb/node_modules/mongodb-core/lib/error.js:29:11)
    at Socket.<anonymous> (/var/foroexodo/nodebb/node_modules/mongodb/node_modules/mongodb-core/lib/connection/connection.js:173:20)
    at Socket.g (events.js:260:16)
    at emitNone (events.js:67:13)
    at Socket.emit (events.js:166:7)
    at Socket._onTimeout (net.js:333:8)
    at _runOnTimeout (timers.js:524:11)
    at _makeTimerTimeout (timers.js:515:3)
    at Timer.unrefTimeout (timers.js:584:5)
8/12 20:43 [6455] - error: MongoError: connection 0 to 127.0.0.1:27017 timed out
    at Function.MongoError.create (/var/foroexodo/nodebb/node_modules/mongodb/node_modules/mongodb-core/lib/error.js:29:11)
    at Socket.<anonymous> (/var/foroexodo/nodebb/node_modules/mongodb/node_modules/mongodb-core/lib/connection/connection.js:173:20)
    at Socket.g (events.js:260:16)
    at emitNone (events.js:67:13)
    at Socket.emit (events.js:166:7)
    at Socket._onTimeout (net.js:333:8)
    at _runOnTimeout (timers.js:524:11)
    at _makeTimerTimeout (timers.js:515:3)
    at Timer.unrefTimeout (timers.js:584:5)
8/12 20:43 [6455] - error:  MongoError: connection 0 to 127.0.0.1:27017 timed out
    at Function.MongoError.create (/var/foroexodo/nodebb/node_modules/mongodb/node_modules/mongodb-core/lib/error.js:29:11)
    at Socket.<anonymous> (/var/foroexodo/nodebb/node_modules/mongodb/node_modules/mongodb-core/lib/connection/connection.js:173:20)
    at Socket.g (events.js:260:16)
    at emitNone (events.js:67:13)
    at Socket.emit (events.js:166:7)
    at Socket._onTimeout (net.js:333:8)
    at _runOnTimeout (timers.js:524:11)
    at _makeTimerTimeout (timers.js:515:3)
    at Timer.unrefTimeout (timers.js:584:5)
[cluster] Child Process (6456) has exited (code: 0, signal: null)
[cluster] Child Process (6455) has exited (code: 0, signal: null)
8/12 20:43 [6473] - error: MongoError: connection 0 to 127.0.0.1:27017 timed out
    at Function.MongoError.create (/var/foroexodo/nodebb/node_modules/mongodb/node_modules/mongodb-core/lib/error.js:29:11)
    at Socket.<anonymous> (/var/foroexodo/nodebb/node_modules/mongodb/node_modules/mongodb-core/lib/connection/connection.js:173:20)
    at Socket.g (events.js:260:16)
    at emitNone (events.js:67:13)
    at Socket.emit (events.js:166:7)
    at Socket._onTimeout (net.js:333:8)
    at _runOnTimeout (timers.js:524:11)
    at _makeTimerTimeout (timers.js:515:3)
    at Timer.unrefTimeout (timers.js:584:5)
8/12 20:43 [6473] - error:  MongoError: connection 0 to 127.0.0.1:27017 timed out
    at Function.MongoError.create (/var/foroexodo/nodebb/node_modules/mongodb/node_modules/mongodb-core/lib/error.js:29:11)
    at Socket.<anonymous> (/var/foroexodo/nodebb/node_modules/mongodb/node_modules/mongodb-core/lib/connection/connection.js:173:20)
    at Socket.g (events.js:260:16)
    at emitNone (events.js:67:13)
    at Socket.emit (events.js:166:7)
    at Socket._onTimeout (net.js:333:8)
    at _runOnTimeout (timers.js:524:11)
    at _makeTimerTimeout (timers.js:515:3)
    at Timer.unrefTimeout (timers.js:584:5)
[cluster] Child Process (6473) has exited (code: 0, signal: null)
8/12 20:43 [6449] - error: MongoError: connection 0 to 127.0.0.1:27017 timed out
    at Function.MongoError.create (/var/foroexodo/nodebb/node_modules/mongodb/node_modules/mongodb-core/lib/error.js:29:11)
    at Socket.<anonymous> (/var/foroexodo/nodebb/node_modules/mongodb/node_modules/mongodb-core/lib/connection/connection.js:173:20)
    at Socket.g (events.js:260:16)
    at emitNone (events.js:67:13)
    at Socket.emit (events.js:166:7)
    at Socket._onTimeout (net.js:333:8)
    at _runOnTimeout (timers.js:524:11)
    at _makeTimerTimeout (timers.js:515:3)
    at Timer.unrefTimeout (timers.js:584:5)
8/12 20:43 [6449] - error:  MongoError: connection 0 to 127.0.0.1:27017 timed out
    at Function.MongoError.create (/var/foroexodo/nodebb/node_modules/mongodb/node_modules/mongodb-core/lib/error.js:29:11)
    at Socket.<anonymous> (/var/foroexodo/nodebb/node_modules/mongodb/node_modules/mongodb-core/lib/connection/connection.js:173:20)
    at Socket.g (events.js:260:16)
    at emitNone (events.js:67:13)
    at Socket.emit (events.js:166:7)
    at Socket._onTimeout (net.js:333:8)
    at _runOnTimeout (timers.js:524:11)
    at _makeTimerTimeout (timers.js:515:3)
    at Timer.unrefTimeout (timers.js:584:5)
[cluster] Child Process (6449) has exited (code: 0, signal: null)

```

**Comment by barisusakli** [comment]
Try to run with `node app.js`

**Comment by exomarty** [comment]
it came back yo life it seems xD
still some errors 

```
 ./nodebb log

Hit Ctrl-C to exit

8/12 20:45 [7045] - info: [database] Checking database indices.
8/12 20:45 [7039] - info: [database] Checking database indices.
8/12 20:45 [7057] - info: [database] Checking database indices.
8/12 20:45 [7045] - info: [database] Checking database indices done!
8/12 20:45 [7063] - info: [database] Checking database indices.
8/12 20:45 [7033] - info: [database] Checking database indices.
8/12 20:45 [7057] - info: [database] Checking database indices done!
8/12 20:45 [7039] - info: [database] Checking database indices done!
8/12 20:45 [7033] - info: [database] Checking database indices done!
8/12 20:45 [7063] - info: [database] Checking database indices done!
8/12 20:45 [7051] - error: Error creating index exception: E11000 duplicate key error index: exodef.objects.$_key_1_value_-1 dup key: { : "ip:recent", : "35.164.70.59" }
8/12 20:45 [7051] - info: [database] Checking database indices done!
8/12 20:45 [7051] - error:  MongoError: exception: E11000 duplicate key error index: exodef.objects.$_key_1_value_-1 dup key: { : "ip:recent", : "35.164.70.59" }
    at Function.MongoError.create (/var/foroexodo/nodebb/node_modules/mongodb/node_modules/mongodb-core/lib/error.js:31:11)
    at /var/foroexodo/nodebb/node_modules/mongodb/node_modules/mongodb-core/lib/connection/pool.js:462:72
    at authenticateStragglers (/var/foroexodo/nodebb/node_modules/mongodb/node_modules/mongodb-core/lib/connection/pool.js:410:16)
    at null.messageHandler (/var/foroexodo/nodebb/node_modules/mongodb/node_modules/mongodb-core/lib/connection/pool.js:444:5)
    at Socket.<anonymous> (/var/foroexodo/nodebb/node_modules/mongodb/node_modules/mongodb-core/lib/connection/connection.js:306:22)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at Socket.Readable.push (_stream_readable.js:111:10)
    at TCP.onread (net.js:537:20)
[cluster] Child Process (7051) has exited (code: 0, signal: null)
8/12 20:45 [7045] - error: MongoError: connection 0 to 127.0.0.1:27017 timed out
    at Function.MongoError.create (/var/foroexodo/nodebb/node_modules/mongodb/node_modules/mongodb-core/lib/error.js:29:11)
    at Socket.<anonymous> (/var/foroexodo/nodebb/node_modules/mongodb/node_modules/mongodb-core/lib/connection/connection.js:173:20)
    at Socket.g (events.js:260:16)
    at emitNone (events.js:67:13)
    at Socket.emit (events.js:166:7)
    at Socket._onTimeout (net.js:333:8)
    at _runOnTimeout (timers.js:524:11)
    at _makeTimerTimeout (timers.js:515:3)
    at Timer.unrefTimeout (timers.js:584:5)
8/12 20:45 [7045] - error:  MongoError: connection 0 to 127.0.0.1:27017 timed out
    at Function.MongoError.create (/var/foroexodo/nodebb/node_modules/mongodb/node_modules/mongodb-core/lib/error.js:29:11)
    at Socket.<anonymous> (/var/foroexodo/nodebb/node_modules/mongodb/node_modules/mongodb-core/lib/connection/connection.js:173:20)
    at Socket.g (events.js:260:16)
    at emitNone (events.js:67:13)
    at Socket.emit (events.js:166:7)
    at Socket._onTimeout (net.js:333:8)
    at _runOnTimeout (timers.js:524:11)
    at _makeTimerTimeout (timers.js:515:3)
    at Timer.unrefTimeout (timers.js:584:5)
[cluster] Child Process (7045) has exited (code: 0, signal: null)
8/12 20:45 [7057] - info: initializing NodeBB ...
8/12 20:45 [7063] - info: initializing NodeBB ...
8/12 20:45 [7039] - info: initializing NodeBB ...
8/12 20:45 [7033] - info: initializing NodeBB ...
8/12 20:45 [7057] - warn: [plugins/nodebb-plugin-poll] Hook `filter:post.save` is deprecated, please use `filter:post.create` instead.
8/12 20:45 [7063] - warn: [plugins/nodebb-plugin-poll] Hook `filter:post.save` is deprecated, please use `filter:post.create` instead.
8/12 20:45 [7039] - warn: [plugins/nodebb-plugin-poll] Hook `filter:post.save` is deprecated, please use `filter:post.create` instead.
8/12 20:45 [7033] - warn: [plugins/nodebb-plugin-poll] Hook `filter:post.save` is deprecated, please use `filter:post.create` instead.

8/12 20:45 [7033] - warn: [plugins/load] The following plugins may not be compatible with your version of NodeBB. This may cause unintended behaviour or crashing. In the event of an unresponsive NodeBB caused by this plugin, run `./nodebb reset -p PLUGINNAME` to disable it.
  * nodebb-plugin-autolock

8/12 20:45 [7057] - info: [reputation-rules] settings loaded
8/12 20:45 [7057] - info: Routes added
8/12 20:45 [7057] - info: NodeBB Ready
8/12 20:45 [7057] - info: Enabling 'trust proxy'
8/12 20:45 [7057] - info: NodeBB is now listening on: 0.0.0.0:4571
8/12 20:46 [7063] - info: [reputation-rules] settings loaded
8/12 20:46 [7063] - info: Routes added
8/12 20:46 [7039] - info: [reputation-rules] settings loaded
8/12 20:46 [7039] - info: Routes added
8/12 20:46 [7039] - info: NodeBB Ready
8/12 20:46 [7039] - info: Enabling 'trust proxy'
8/12 20:46 [7039] - info: NodeBB is now listening on: 0.0.0.0:4568
8/12 20:46 [7033] - info: [reputation-rules] settings loaded
8/12 20:46 [7033] - info: Routes added
8/12 20:46 [7063] - info: NodeBB Ready
8/12 20:46 [7063] - info: Enabling 'trust proxy'
8/12 20:46 [7063] - info: NodeBB is now listening on: 0.0.0.0:4572
8/12 20:46 [7033] - info: NodeBB Ready
8/12 20:46 [7033] - info: Enabling 'trust proxy'
8/12 20:46 [7033] - info: NodeBB is now listening on: 0.0.0.0:4567

```

**Comment by exomarty** [comment]
checking now that command

safe to delete all this?

![screenshot_5](https://cloud.githubusercontent.com/assets/10746278/21025221/e6259ffe-bd87-11e6-980b-de8affeb85f2.png)

**Comment by barisusakli** [comment]
Verify they are actualle dupes by running a find command with the ip like this.

`db.objects.find({_key:"ip:recent", value: "<insert_problem_ip>"}).pretty();`

If you get 2 documents then you can delete one.

As always backup your database before running anything.

**Comment by exomarty** [comment]
deleted 30 of each 1by1 on analytics:pageviews , ip:recent, analytics:errors:404

but seems a never ending task :/

```
NodeBB is now listening on: 0.0.0.0:4570
8/12 21:43 [14509] - error: Error creating index exception: E11000 duplicate key error index: exodef.objects.$_key_1_value_-1 dup key: { : "analytics:posts:byCid:20", : "1481133600000" }
8/12 21:43 [14509] - info: [database] Checking database indices done!
8/12 21:43 [14509] - error:  MongoError: exception: E11000 duplicate key error index: exodef.objects.$_key_1_value_-1 dup key: { : "analytics:posts:byCid:20", : "1481133600000" }
    at Function.MongoError.create (/var/foroexodo/nodebb/node_modules/mongodb/node_modules/mongodb-core/lib/error.js:31:11)
    at /var/foroexodo/nodebb/node_modules/mongodb/node_modules/mongodb-core/lib/connection/pool.js:462:72
    at authenticateStragglers (/var/foroexodo/nodebb/node_modules/mongodb/node_modules/mongodb-core/lib/connection/pool.js:410:16)
    at null.messageHandler (/var/foroexodo/nodebb/node_modules/mongodb/node_modules/mongodb-core/lib/connection/pool.js:444:5)
    at Socket.<anonymous> (/var/foroexodo/nodebb/node_modules/mongodb/node_modules/mongodb-core/lib/connection/connection.js:306:22)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at Socket.Readable.push (_stream_readable.js:111:10)
    at TCP.onread (net.js:537:20)
[cluster] Child Process (14509) has exited (code: 0, signal: null)

```

**Comment by exomarty** [comment]
Any solution to remove all this wierd keys on a bulk or a fix comming soon?

**Comment by exomarty** [comment]
after deleting yesterday all duplicated keys on ip:recent they are back again today
this bug wont be solved with manual key removing

![screenshot_6](https://cloud.githubusercontent.com/assets/10746278/21074887/af38247a-bf04-11e6-8799-3fa438837b1e.png)

**Comment by barisusakli** [comment]
I would make sure you have the correct indexes on the correct database. One of your previous comments said you were on the wrong database.

```
> db.objects.getIndexes()
[
        {
                "v" : 1,
                "key" : {
                        "_id" : 1
                },
                "name" : "_id_",
                "ns" : "0.objects"
        },
        {
                "v" : 1,
                "key" : {
                        "_key" : 1,
                        "score" : -1
                },
                "name" : "_key_1_score_-1",
                "ns" : "0.objects",
                "background" : true
        },
        {
                "v" : 1,
                "unique" : true,
                "key" : {
                        "_key" : 1,
                        "value" : -1
                },
                "name" : "_key_1_value_-1",
                "ns" : "0.objects",
                "background" : true,
                "sparse" : true
        },
        {
                "v" : 1,
                "key" : {
                        "expireAt" : 1
                },
                "name" : "expireAt_1",
                "ns" : "0.objects",
                "expireAfterSeconds" : 0,
                "background" : true
        }
]
```

Those are the correct indexes on the objects collection.

**Comment by barisusakli** [comment]
So you are missing the correct indexes, create those and clear the duplicated date and problem should be fixed.

**Comment by exomarty** [comment]
Not sure how to correct that indexes

**Comment by barisusakli** [comment]
You will call createIndex on the correct db.

`db.objects.createIndex({_key: 1, value: -1}, {unique: 1, sparse: true, background: true});`

https://docs.mongodb.com/manual/reference/method/db.collection.createIndex/#definition

**Comment by exomarty** [comment]
sorry but didnt work 

![screenshot_12](https://cloud.githubusercontent.com/assets/10746278/21165252/8199600a-c19e-11e6-9d7b-68ee8df8054e.png)

but still showing same index


![screenshot_13](https://cloud.githubusercontent.com/assets/10746278/21165261/97a57532-c19e-11e6-8cab-af1a4f6a1233.png)

**Comment by barisusakli** [comment]
Maybe try `db.objects.createIndex({_key: 1, value: -1}, {unique: true, sparse: true, background: true});`

**Comment by exomarty** [comment]
no working, same with that new command

**Comment by exomarty** [comment]
Any idea? I keep having downtimes because of this

**Comment by jarey** [comment]
Hello,

Just got the backup from @exomarty database, and restored it.

Actually, the database seems to not have, the index create mentioned above.

After creating it, with no erros, something extrange (in my opinion) happens. I can see the index using the robomongo interface, as my db client, BUT i can not see the index using the comand db.objects.getIndexes().

I am not very familiar with mongodb, but this doesn´t happen on my fresh dev installation, where the index is shown with that command.

Would you have any idea what this happens? @barisusakli @julianlam @psychobunny .

@exomarty forum is crashing every 10 minutes because of this problem. Any help it is greatly appreciated.

Thanks in advance.

![image](https://cloud.githubusercontent.com/assets/5025224/21278455/908353d4-c3db-11e6-8619-532f6edcaaad.png)

**Comment by barisusakli** [comment]
Just use the mongoshell to create the index and check for errors. If create index command fails it will show the errors.

**Comment by exomarty** [comment]
It doesnt show any error as it was shown before

https://cloud.githubusercontent.com/assets/10746278/21165252/8199600a-c19e-11e6-9d7b-68ee8df8054e.png

**Comment by jarey** [comment]
It does throw duplication errors if the command is executed by mongoshell instead of robomongo. Maybe the problem it's just that. I couldnt figure out a way of removing all the correct dups in your backup without destroying the database; but it replicates on your backup restored on my local instance.

Maybe you should try to remove duplicates and just execute the index creation with the mongoshell (without using robomongo at all), because it does seem that it its hiding some errors.

Give it a try and let us know.

**Comment by exomarty** [comment]
using now mongoshell
after deleting many duplicates from the createIndex error i get this now...


> db.objects.createIndex({_key: 1, value: -1}, {unique: 1, sparse: true, background: true});
{
        "createdCollectionAutomatically" : false,
        "numIndexesBefore" : 3,
        "errmsg" : "exception: Btree::insert: key too large to index, failing exodef.objects.$_key_1_value_-1 1194 { : \"errors:404\", : \"/topic/17979/Si%20veis%20alg%C3%BAn%20GIF%2                              0bueno%20y%20quer%C3%A9is%20poner%20una%20frase%20o%20algo%20dejad%20aqu%C3%AD%20el%20gif%20y%20la%20frase%...\" }",
        "code" : 17280,
        "ok" : 0
}

**Comment by barisusakli** [comment]
You can safely delete the 404 error log with `db.objects.remove({_key: "errors:404"});`

**Comment by exomarty** [comment]
finally solved using only mongoshell, deleting duplicates and earing 404 error on nodebb admin
i write here command for bulk delete duplicates
take care with core keys like "global" or "config"
just chnage the keyname on the code below

```
db.objects.aggregate([
  // discard selection criteria, You can remove "$match" section if you want
  { $match: { _key: "analytics:uniquevisitors"}
  },
  { $group: {
    _id: {value: "$value"}, // can be grouped on multiple properties
    dups: { "$addToSet": "$_id" },
    count: { "$sum": 1 }
  }},
  { $match: {
    count: { "$gt": 1 }    // Duplicates considered as count greater than one
  }}
],
{allowDiskUse: true}       // For faster processing if set is larger
)               // You can display result until this and check duplicates
.forEach(function(doc) {
    doc.dups.shift();      // First element skipped for deleting
    db.objects.remove({_id : {$in: doc.dups }});  // Delete remaining duplicates
})
```
